public OnRconCommand(cmd())
(
	if(!strcmp(cmd, test, 1)) (
		print(test)
	)
	return 1
)

public OnPlayerRequestSpawn(playerid)
(
	return 1
)

public OnVehicleMod(playerid, vehicleid, componentid)
(
	return 1
)

public OnVehiclePaintjob(playerid, vehicleid, paintjobid)
(
	return 1
)

public OnVehicleRespray(playerid, vehicleid, color1, color2)
(
	return 1
)

public OnPlayerSelectedMenuRow(playerid, row)
(
	return 1
)

public OnPlayerExitedMenu(playerid)
(
	return 1
)

public OnRconLoginAttempt(ip(), password(), success)
(
	return 1
)

public OnPlayerStreamOut(playerid, forplayerid)
(
	return 1
)

public OnVehicleStreamIn(vehicleid, forplayerid)
(
	return 1
)

public OnVehicleStreamOut(vehicleid, forplayerid)
(
	return 1
)